#ifndef __COMPUTATIONALGRAPH_DEBUG_H__
#define __COMPUTATIONALGRAPH_DEBUG_H__

#include <string>

#define UNKNOWN_TYPE_ERROR 0
#define DEVISION_BY_ZERO 1
#define PLACEHOLDER_MISSING 2
#define NO_MATCH_OPERATOR_FOR 3
#define NON_POSITIVE_VALUE_IN_LOG 4

#define EVALUATE_NODE_OF_ILLEGAL_TYPE 6
#define NODE_NOT_FOUND 7
//#define COMPUTE_ERROR 8

#define ILLEGAL_EXPRESSION 10

#define TRY_TO_GET_VALUE_FROM_OPERATOR 12
#define EVALUATE_NODE_OF_ILLEGAL_TYPE_BY_SETCONSTANT 13

#define UNKNOWN_NODE_TYPE 15
#define PARAMETER_MISSING_IN_EVAL 16
#define DATA_OUT_OF_RANGE 17

#define NODE_REDEFINED 19
#define UNNECESSARY_ASSIGNMENT 20
#define ASSERTION_FAILED 21
#define PARAMETER_COUNT_ERROR 22
#define DERIVATIVE_TO_CONSTANT 23
#define DERIVATIVE_NOT_AVAILABLE 24
#define TRY_HIGHER_DERIVATIVE 25
#define GRAD_OPERATOR_NOT_FOUND 26
#define AT_OPERATOR_NOT_FOUND 27
void throw_error ( int v , std::string s = "" ) ;

#endif